spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  jpa:
    show-sql: true
server:
   context-path: /sell
   port: 8080
  #URL的前缀 例如:/sell/xxx/xx
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: i:/var/log/tomcat/
#  file: i:/var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug